<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AllowedValues\**" />
    <Compile Remove="Rates\**" />
    <EmbeddedResource Remove="AllowedValues\**" />
    <EmbeddedResource Remove="Rates\**" />
    <None Remove="AllowedValues\**" />
    <None Remove="Rates\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Throw" />
    <PackageReference Include="Wrak.Extensions" />
  </ItemGroup>

</Project>
