trigger:
  - test

pool:
  vmImage: 'ubuntu-latest'

variables:
  build.configuration: 'Release'
  serviceConnection: 'your-test-arm-svc-cnn'

stages:

# ----------------------
# Build Stage
# ----------------------
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: AzureKeyVault@2
      displayName: 'Pull Secrets from Azure Key Vault'
      inputs:
        azureSubscription: '$(serviceConnection)'
        KeyVaultName: 'your-test-key-vault-name'
        SecretsFilter: '*'
        RunAsPreJob: true

    - task: ReplaceTokens@6
      displayName: 'Replace Test Config Tokens'
      inputs:
        targetFiles: '**/appsettings.IntegrationTests.json'
        enableTokenFile: true
        encoding: 'utf-8'
        tokenPrefix: '#{'
        tokenSuffix: '}#'
        keepToken: false
        actionOnMissing: 'warn'

    - task: ReplaceTokens@6
      displayName: 'Replace App Config Tokens'
      inputs:
        targetFiles: '**/appsettings.Test.json'
        enableTokenFile: true
        encoding: 'utf-8'
        tokenPrefix: '#{'
        tokenSuffix: '}#'
        keepToken: false
        actionOnMissing: 'warn'

    - task: PowerShell@2  
      displayName: 'Set Build Number'  
      inputs:  
        targetType: 'inline'  
        script: |  
            Set-Content -Path .\Wrak.Clean.Blazor.Web\BuildInfo.cs -Value "namespace Wrak.Clean.Blazor.Web; public static class BuildInfo { public const string Build = ""$(build.buildnumber)""; }"  

    - task: UseDotNet@2  
      displayName: 'Use .NET SDK'  
      inputs:  
        packageType: sdk  
        version: '10.0.x'

    - task: DotNetCoreCLI@2
      displayName: 'Restore Solution'
      inputs:
        command: 'restore'
        projects: '**/*.slnx'
        feedsToUse: 'config'
        nugetConfigPath: 'nuget.config'

    - task: PowerShell@2
      displayName: 'Verify Pinned Package Versions'
      inputs:
        filePath: '$(Build.SourcesDirectory)/Verify-Package-Versions.ps1'
        pwsh: true

    - task: DotNetCoreCLI@2  
      displayName: 'Build Solution'  
      inputs:  
        command: 'build'  
        projects: '**/*.slnx'
        arguments: '--configuration $(build.configuration) /p:SourceRevisionId=$(Build.SourceVersion)'

    - task: DotNetCoreCLI@2
      displayName: 'Run Tests'
      inputs:
        command: 'test'
        projects: '**/*Tests.csproj'
        publishTestResults: true
        arguments: '--configuration $(build.configuration) --no-build'

    - task: DotNetCoreCLI@2
      displayName: 'Publish Blazor Server App'
      inputs:
        command: publish
        publishWebProjects: true
        arguments: '--configuration $(build.configuration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

# ----------------------
# Deploy Stage
# ----------------------
- stage: Deploy
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployJob
    environment: 'Test'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - task: AzureWebApp@1
            displayName: 'Deploy to Azure Web App'
            inputs:
              azureSubscription: '$(serviceConnection)'
              appType: 'webApp'
              appName: 'your-test-webapp-name'
              package: '$(Pipeline.Workspace)/drop/**/*.zip'
